name: validate-and-archive
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Run evaluation
        run: python run_eval.py --n 6 --protocol protocols/observation_layer_v1_1.json --seed 42
      - name: Validate results
        run: python validate.py --strict --results results/summary.json
      - name: Upload results
        uses: actions/upload-artifact@v4
        with: 
          name: results
          path: results/